version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - .:/workspaces:cached
      # Uncomment to share maven cache, doesn't work in Github Codespaces.
      # - ~/.m2:/root/.m2 # maven cache
    command: sleep infinity

# Add your other services here.